/**
 * Copyright 2008-2019, Province of British Columbia
 *  All rights reserved.
 */
package ca.bc.gov.ols.router.open511.enums;

public enum EventSubtype {
	ACCIDENT,
	SPILL,
	OBSTRUCTION,
	HAZARD,
	ROAD_MAINTENANCE,
	ROAD_CONSTRUCTION,
	EMERGENCY_MAINTENANCE,
	PLANNED_EVENT,
	CROWD,
	HAIL,
	THUNDERSTORM,
	HEAVY_DOWNPOUR,
	STRONG_WINDS,
	BLOWING_DUST,
	SANDSTORM,
	INSECT_SWARMS,
	AVALANCHE_HAZARD,
	SURFACE_WATER_HAZARD,
	MUD,
	LOOSE_GRAVEL,
	OIL_ON_ROADWAY,
	FIRE,
	SIGNAL_LIGHT_FAILURE,
	PARTLY_ICY,
	ICE_COVERED,
	PARTLY_SNOW_PACKED,
	SNOW_PACKED,
	PARTLY_SNOW_COVERED,
	SNOW_COVERED,
	DRIFTING_SNOW,
	POOR_VISIBILITY,
	ALMOST_IMPASSABLE,
	PASSABLE_WITH_CARE;
}
